import React from 'react';
import Head from 'next/head';

const Login = () => {
  return (
    <div className="w-full h-full flex rounded items-center register px-4 justify-center">
      <Head>
        <title>Mangas | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-white w-[50vh] rounded-xl z-10">
        <div className="bg-[#141324] p-4 rounded-t-xl text-center">
          <h2 className="text-3xl font-semibold">Login</h2>
        </div>
        <from className="flex gap-4  text-black flex-col my-2 p-6">
          <div className="flex flex-col gap-2">
            <label className="font-semibold text-center">E-mail</label>
            <input type="text" className=" border-2 rounded-xl border-pink-500 p-2" />
          </div>
          <div className="flex flex-col gap-2">
            <label className="font-semibold text-center">Password</label>
            <input type="password" className="border-2 rounded-xl border-pink-500 p-2" />
          </div>
          <button className="bg-pink-900 max-w-[max-content] mt-2 mx-auto py-2 px-3 rounded-xl font-semibold text-white">
            Sign Up
          </button>
        </from>
      </div>
    </div>
  );
};

export default Login;
