import Head from 'next/head';

import Hero from '../components/Hero/Hero';
import MangaSlider from './../components/MangaSlider/MangaSlider';
import 'react-slideshow-image/dist/styles.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <MangaSlider />
    </div>
  );
}
