import Head from 'next/head';

import Hero from '../components/Hero/Hero';
import MangaSlider from './../components/MangaSlider/MangaSlider';
import MangaTop from './../components/MangaTop/MangaTop';
import AnimeTop from './../components/AnimeTop/AnimeTop';

export default function Home({manga, anime}) {
  return (
    <div>
      <Head>
        <title>Mangas | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero />
        <MangaSlider />
        <MangaTop manga={manga} />
        <AnimeTop anime={anime} />
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const request = await fetch('https://api.jikan.moe/v4/top/anime').then(res => res.json());

  const req = await fetch('https://api.jikan.moe/v4/top/manga').then(res => res.json());

  return {
    props: {
      manga: request,
      anime: req,
    },
  };
}
