import Head from 'next/head';
import {AiFillStar} from 'react-icons/ai';

export const getStaticPaths = async () => {
  const res = await fetch('https://kitsu.io/api/edge/trending/manga');
  const data = await res.json();

  const paths = data.data.map(mang => {
    return {
      params: {
        id: mang.id.toString(),
      },
    };
  });
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async context => {
  const id = context.params.id;
  const res = await fetch(`https://kitsu.io/api/edge/manga/${id}`);
  const data = await res.json();

  return {
    props: {
      manga: data,
    },
  };
};

const Mangas = ({manga}) => {
  return (
    <div
      className="w-full h-screen bg-cover bg-center bg-no-repeat relative"
      style={{
        backgroundImage: `url(
          ${manga.data.attributes.posterImage.original}
        )`,
      }}
    >
      <Head>
        <title>Mangas | {manga.data.attributes.titles.en_jp}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <div className="flex flex-col md:flex-row gap-10 items-center justify-center">
          <div className="max-w-[500px] my-10 z-10 mb-10 md:mb-0">
            <span className="font-semibold text-pink-400">
              {manga.data.attributes.titles.ja_jp}
            </span>
            <h2 className="my-3 text-3xl font-bold">{manga.data.attributes.titles.en_jp}</h2>
            <div className=" my-2 flex item-center gap-2">
              <span>
                <AiFillStar size={20} color="#ffd700" />
              </span>
              {manga.data.attributes.averageRating} %
            </div>
            <p className="mb-3 font-semibold">{manga.data.attributes.synopsis}</p>
          </div>
          <div>
            <div className="absolute top-0 left-0 right-0 bottom-0 z-[1] bg-black/75" />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Mangas;
