import React from 'react'
import Head from 'next/head'

function Register() {
  return (
    <div className="register flex h-full w-full items-center justify-center rounded px-4 shadow-xl">
      <Head>
        <title>Mangas | Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="z-10 w-[50vh] rounded-xl bg-white">
        <div className="rounded-t-xl bg-[#141324] p-4 text-center">
          <h2 className="text-3xl font-semibold">Register</h2>
        </div>
        <from className="my-2 flex  flex-col gap-4 p-6 text-black">
          <div className="flex flex-col gap-2">
            <label className="text-center font-semibold">E-mail</label>
            <input
              type="text"
              className=" rounded-xl border-2 border-pink-500 p-2"
            />
          </div>
          <div className="flex flex-col gap-2">
            <label className="text-center font-semibold">Password</label>
            <input
              type="password"
              className="rounded-xl border-2 border-pink-500 p-2"
            />
          </div>
          <button
            type="button"
            className="mx-auto mt-2 max-w-[max-content] rounded-xl bg-pink-900 py-2 px-3 font-semibold text-white"
          >
            Sign In
          </button>
        </from>
      </div>
    </div>
  )
}

export default Register
