import Image from 'next/image';
import Head from 'next/head';
import {AiFillStar} from 'react-icons/ai';
import ReactPlayer from 'react-player/lazy';

export const getStaticPaths = async () => {
  const res = await fetch('https://api.jikan.moe/v4/top/anime');
  const data = await res.json();

  const paths = data.data.map(anim => {
    return {
      params: {
        id: anim.mal_id.toString(),
      },
    };
  });
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async context => {
  const id = context.params.id;
  const res = await fetch(`https://api.jikan.moe/v4/anime/${id}`);
  const data = await res.json();

  return {
    props: {
      anime: data,
    },
  };
};

const Animes = ({anime}) => {
  return (
    <div>
      <Head>
        <title>Mangas | {anime.data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-10 my-10 ">
        <div className="z-[20]">
          <div>
            <div className="block lg:flex gap-10">
              <div className="z-[50] max-w-[500px] mb-10  mx-auto">
                <span className="font-semibold text-pink-400">{anime.data.title}</span>
                <h2 className="my-3 text-3xl font-bold">{anime.data.title}</h2>
                <div className=" my-2 flex item-center gap-2">
                  <span>
                    <AiFillStar size={20} color="#ffd700" />
                  </span>
                  {anime.data.score} %
                </div>
                <p className="mb-3 font-semibold">{anime.data.synopsis}</p>
              </div>
              <div className="z-10 rounded-xl flex items-center justify-center px-2 ">
                <ReactPlayer url={anime.data.trailer.url} controls className="mx-auto" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Animes;
